import { useState } from 'react';
import { FileCode, Clock, AlertCircle, CheckCircle, ChevronDown, ChevronUp, Download } from 'lucide-react';

interface ReviewResultsProps {
  data: {
    filename: string;
    language: string;
    stats: {
      totalIssues: number;
      critical: number;
      high: number;
      medium: number;
      low: number;
      score: number;
    };
    issues: Array<{
      type: string;
      severity: string;
      message: string;
      line?: number;
      column?: number;
      suggestion?: string;
    }>;
    suggestions: any[];
    timestamp: string;
  };
}

export default function ReviewResults({ data }: ReviewResultsProps) {
  const [expandedIssue, setExpandedIssue] = useState<number | null>(null);

  const getSeverityBadge = (severity: string) => {
    const badges = {
      critical: 'bg-red-100 text-red-800 border-red-300',
      high: 'bg-orange-100 text-orange-800 border-orange-300',
      medium: 'bg-yellow-100 text-yellow-800 border-yellow-300',
      low: 'bg-blue-100 text-blue-800 border-blue-300'
    };
    return badges[severity as keyof typeof badges] || 'bg-gray-100 text-gray-800';
  };

  const getSeverityIcon = (severity: string) => {
    if (severity === 'critical' || severity === 'high') {
      return <AlertCircle className="w-5 h-5" />;
    }
    return <CheckCircle className="w-5 h-5" />;
  };

  const handleExport = (format: 'json' | 'html') => {
    const dataStr = format === 'json' 
      ? JSON.stringify(data, null, 2)
      : generateHTML();
    
    const blob = new Blob([dataStr], { type: format === 'json' ? 'application/json' : 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `codeblaster-${data.filename}-${Date.now()}.${format}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const generateHTML = () => {
    return `
<!DOCTYPE html>
<html>
<head>
  <title>CodeBlaster Report - ${data.filename}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }
    .container { max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
    h1 { color: #6366f1; border-bottom: 3px solid #6366f1; padding-bottom: 10px; }
    .stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin: 20px 0; }
    .stat-card { background: #f8f9fa; padding: 20px; border-radius: 8px; border-left: 4px solid #6366f1; }
    .issue { background: #fff; border: 1px solid #e0e0e0; padding: 15px; margin: 10px 0; border-radius: 5px; }
    .critical { border-left: 4px solid #ef4444; }
    .high { border-left: 4px solid #f97316; }
    .medium { border-left: 4px solid #eab308; }
    .low { border-left: 4px solid #3b82f6; }
    .badge { display: inline-block; padding: 4px 12px; border-radius: 12px; font-size: 12px; font-weight: bold; }
  </style>
</head>
<body>
  <div class="container">
    <h1>🚀 CodeBlaster AI Analysis Report</h1>
    <p><strong>File:</strong> ${data.filename}</p>
    <p><strong>Language:</strong> ${data.language}</p>
    <p><strong>Timestamp:</strong> ${new Date(data.timestamp).toLocaleString()}</p>
    
    <div class="stats">
      <div class="stat-card"><h3>Score</h3><h2>${data.stats.score}/100</h2></div>
      <div class="stat-card"><h3>Total Issues</h3><h2>${data.stats.totalIssues}</h2></div>
      <div class="stat-card"><h3>Critical</h3><h2>${data.stats.critical}</h2></div>
      <div class="stat-card"><h3>High</h3><h2>${data.stats.high}</h2></div>
    </div>
    
    <h2>Issues Found</h2>
    ${data.issues.map(issue => `
      <div class="issue ${issue.severity}">
        <span class="badge">${issue.severity.toUpperCase()}</span>
        <h3>${issue.type}</h3>
        <p>${issue.message}</p>
        ${issue.line ? `<p><small>Line ${issue.line}${issue.column ? `:${issue.column}` : ''}</small></p>` : ''}
        ${issue.suggestion ? `<p><strong>Suggestion:</strong> ${issue.suggestion}</p>` : ''}
      </div>
    `).join('')}
    
    <footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #e0e0e0; text-align: center; color: #666;">
      Generated by CodeBlaster AI • Created by attazy
    </footer>
  </div>
</body>
</html>
    `;
  };

  return (
    <div className="bg-white rounded-xl shadow-elegant p-6 card-hover border border-gray-100">
      {/* Header */}
      <div className="flex items-center justify-between mb-6 pb-4 border-b-2 border-gradient-to-r from-purple-200 to-blue-200">
        <div>
          <h2 className="text-2xl font-bold text-gray-800 flex items-center">
            <div className="p-2 bg-gradient-to-br from-blue-500 to-indigo-500 rounded-lg mr-3">
              <FileCode className="text-white" size={20} />
            </div>
            Analysis Results
          </h2>
          <p className="text-sm text-gray-600 mt-2 ml-11">
            <span className="font-bold text-purple-600">{data.filename}</span> 
            <span className="mx-2">•</span>
            <span className="bg-blue-100 text-blue-700 px-3 py-1 rounded-full text-xs font-semibold">
              {data.language}
            </span>
          </p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={() => handleExport('json')}
            className="px-4 py-2 bg-gradient-to-r from-blue-500 to-blue-600 text-white rounded-lg hover:shadow-lg transition-all duration-300 flex items-center text-sm font-semibold hover:scale-105"
          >
            <Download className="w-4 h-4 mr-2" />
            JSON
          </button>
          <button
            onClick={() => handleExport('html')}
            className="px-4 py-2 bg-gradient-to-r from-purple-500 to-purple-600 text-white rounded-lg hover:shadow-lg transition-all duration-300 flex items-center text-sm font-semibold hover:scale-105"
          >
            <Download className="w-4 h-4 mr-2" />
            HTML
          </button>
        </div>
      </div>

      {/* Timestamp */}
      <div className="flex items-center text-sm text-gray-600 mb-6 bg-gray-50 px-4 py-2 rounded-lg border border-gray-200">
        <Clock className="w-4 h-4 mr-2 text-purple-500" />
        <span className="font-medium">Analyzed on {new Date(data.timestamp).toLocaleString()}</span>
      </div>

      {/* Issues List */}
      <div className="space-y-4">
        <h3 className="text-xl font-bold text-gray-800 mb-4 flex items-center gap-2">
          <span className="text-2xl">🔍</span>
          Issues Found 
          <span className="bg-gradient-to-r from-purple-100 to-blue-100 text-purple-700 px-4 py-1 rounded-full text-sm font-bold border-2 border-purple-200">
            {data.stats.totalIssues}
          </span>
        </h3>

        {data.issues.length === 0 ? (
          <div className="text-center py-12 bg-gradient-to-br from-green-50 to-emerald-50 rounded-xl border-2 border-green-200">
            <CheckCircle className="w-20 h-20 text-green-500 mx-auto mb-4 animate-pulse" />
            <p className="text-2xl font-bold text-green-700 mb-2">No Issues Found!</p>
            <p className="text-gray-600 text-base">Your code looks great 🎉</p>
            <div className="mt-4 flex justify-center gap-3 text-sm">
              <span className="bg-green-100 text-green-700 px-4 py-2 rounded-full font-semibold">
                ✓ Clean Code
              </span>
              <span className="bg-green-100 text-green-700 px-4 py-2 rounded-full font-semibold">
                ✓ Best Practices
              </span>
              <span className="bg-green-100 text-green-700 px-4 py-2 rounded-full font-semibold">
                ✓ Secure
              </span>
            </div>
          </div>
        ) : (
          data.issues.map((issue, index) => (
            <div
              key={index}
              className="border-2 border-gray-200 rounded-xl overflow-hidden hover:shadow-lg transition-all duration-300 bg-white card-hover"
            >
              <div
                className="p-5 cursor-pointer flex items-start justify-between bg-gradient-to-r from-gray-50 to-gray-100 hover:from-purple-50 hover:to-blue-50 transition-all duration-300"
                onClick={() => setExpandedIssue(expandedIssue === index ? null : index)}
              >
                <div className="flex items-start flex-1">
                  <div className={`mr-4 p-2 rounded-lg ${
                    issue.severity === 'critical' ? 'bg-red-100 text-red-600' :
                    issue.severity === 'high' ? 'bg-orange-100 text-orange-600' :
                    issue.severity === 'medium' ? 'bg-yellow-100 text-yellow-600' :
                    'bg-blue-100 text-blue-600'
                  }`}>
                    {getSeverityIcon(issue.severity)}
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center gap-3 mb-2">
                      <span className={`px-4 py-1 text-xs font-black rounded-full border-2 ${getSeverityBadge(issue.severity)}`}>
                        {issue.severity.toUpperCase()}
                      </span>
                      <span className="font-bold text-gray-900 text-lg">{issue.type}</span>
                    </div>
                    <p className="text-gray-700 font-medium">{issue.message}</p>
                    {issue.line && (
                      <div className="mt-2 inline-flex items-center gap-2 bg-gray-200 px-3 py-1 rounded-md text-xs font-mono text-gray-700">
                        <span className="font-bold">Line {issue.line}</span>
                        {issue.column && <span>: Column {issue.column}</span>}
                      </div>
                    )}
                  </div>
                </div>
                <div className="ml-4 p-2 rounded-lg bg-white">
                  {expandedIssue === index ? (
                    <ChevronUp className="w-5 h-5 text-gray-600" />
                  ) : (
                    <ChevronDown className="w-5 h-5 text-gray-600" />
                  )}
                </div>
              </div>

              {expandedIssue === index && issue.suggestion && (
                <div className="p-5 bg-gradient-to-br from-blue-50 to-indigo-50 border-t-2 border-blue-200">
                  <p className="text-sm font-bold text-blue-900 mb-2 flex items-center gap-2">
                    <span className="text-xl">💡</span> Suggested Fix:
                  </p>
                  <p className="text-sm text-blue-800 font-medium leading-relaxed bg-white p-4 rounded-lg border border-blue-200">
                    {issue.suggestion}
                  </p>
                </div>
              )}
            </div>
          ))
        )}
      </div>
    </div>
  );
}
